"""
go to waterfall South
    options:
        - swim:
            - die
                            -
                            -
                            -
                                            -
                                            -
                                            - 
                                                            -
                                                            -
                                                            -
                                                                            -
                                                                            -
                                                                            -
            -
                            -
                            -
                            -
                                            -
                                            -
                                            -
                                                            -
                                                            -
                                                            -
                                                                            -
                                                                            -
                                                                            -
            -
                            -
                            -
                            -
                                            -
                                            -
                                            -
                                                            -
                                                            -
                                                            -
                                                                            -
                                                                            -
                                                                            -

        - collect water:
            - die
                            -
                            -
                            -
                                            -
                                            -
                                            -
                                                            -
                                                            -
                                                            -
                                                                            -
                                                                            -
                                                                            -
            -
                            -
                            -
                            -
                                            -
                                            -
                                            -
                                                            -
                                                            -
                                                            -
                                                                            -
                                                                            -
                                                                            -
            -
                            -
                            -
                            -
                                            -
                                            -
                                            -
                                                            -
                                                            -
                                                            -
                                                                            -
                                                                            -
                                                                            -
        - go back(North):
            - go back to START.
"""
